SELECT DTM.*, TB.TOP_EXPT_BALISE_BDF                      --CARTO
FROM DMUP10DTWH_RST_0.F_ALIM_CARTO_BDF_MENS DTM 
INNER JOIN DMUP10DTWH_SOC_0.TYP_BALISE_BDF_CATS TB 
ON TB.CD_BALISE_BDF = DTM.CD_BALISE_BDF 
WHERE ID_MOIS = DATE '2025-12-01' ;


SELECT DTM.*, TB.TOP_EXPT_BALISE_BDF                     --PREV ECO
FROM DMUP10DTWH_RST_0.F_ALIM_PREV_ECO_MENS DTM 
INNER JOIN DMUP10DTWH_SOC_0.TYP_BALISE_BDF_CATS TB 
ON TB.CD_BALISE_BDF = DTM.CD_BALISE_BDF 
WHERE ID_MOIS = DATE '2025-12-01' ;

-----------------------------------------------------------------------------------------------------Test


SELECT DTM.*, TB.TOP_EXPT_BALISE_BDF                  --CARTO
FROM EchangesEtFlux.F_ALIM_CARTO_BDF_MENS DTM 
INNER JOIN EchangesEtFlux.TYP_BALISE_BDF_CATS TB 
ON TB.CD_BALISE_BDF = DTM.CD_BALISE_BDF 
WHERE ID_MOIS = DATE '2026-02-01' ;


SELECT DTM.*, TB.TOP_EXPT_BALISE_BDF               --PREV ECO
FROM EchangesEtFlux.F_ALIM_PREV_ECO_MENS DTM 
INNER JOIN EchangesEtFlux.TYP_BALISE_BDF_CATS TB 
ON TB.CD_BALISE_BDF = DTM.CD_BALISE_BDF 
WHERE ID_MOIS = DATE '2026-02-01' ;
